# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyQt/JanelaListaAlimentos.ui'
#
# Created: Thu Oct 22 15:35:13 2009
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from Global import *

class Ui_JanelaListaAlimentos(object):
    def setupUi(self, JanelaListaAlimentos):
        JanelaListaAlimentos.setObjectName("JanelaListaAlimentos")
        JanelaListaAlimentos.resize(915, 519)
        
        self.label_4 = QtGui.QLabel(JanelaListaAlimentos)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 921, 521))
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        
        self.label = QtGui.QLabel(JanelaListaAlimentos)
        self.label.setGeometry(QtCore.QRect(600, 290, 301, 251))
        self.label.setPixmap(QtGui.QPixmap(MY_DIR_IMG + "bananas.jpg"))
        self.label.setObjectName("label")
        
        self.listaAlimentos = QtGui.QListWidget(JanelaListaAlimentos)
        self.listaAlimentos.setGeometry(QtCore.QRect(10, 60, 281, 411))
        self.listaAlimentos.setObjectName("listaAlimentos")
        self.tbPropriedades = QtGui.QTableWidget(JanelaListaAlimentos)
        self.tbPropriedades.setGeometry(QtCore.QRect(330, 100, 291, 411))
        self.tbPropriedades.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tbPropriedades.setColumnCount(1)
        self.tbPropriedades.setObjectName("tbPropriedades")
        self.tbPropriedades.setColumnCount(1)
        self.tbPropriedades.setRowCount(28)
        item = QtGui.QTableWidgetItem()
        self.tbPropriedades.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbPropriedades.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tbPropriedades.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tbPropriedades.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tbPropriedades.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tbPropriedades.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tbPropriedades.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tbPropriedades.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tbPropriedades.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tbPropriedades.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tbPropriedades.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tbPropriedades.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tbPropriedades.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tbPropriedades.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tbPropriedades.setVerticalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tbPropriedades.setVerticalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.tbPropriedades.setVerticalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.tbPropriedades.setVerticalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        self.tbPropriedades.setVerticalHeaderItem(18, item)
        item = QtGui.QTableWidgetItem()
        self.tbPropriedades.setVerticalHeaderItem(19, item)
        item = QtGui.QTableWidgetItem()
        self.tbPropriedades.setVerticalHeaderItem(20, item)
        item = QtGui.QTableWidgetItem()
        self.tbPropriedades.setVerticalHeaderItem(21, item)
        item = QtGui.QTableWidgetItem()
        self.tbPropriedades.setVerticalHeaderItem(22, item)
        item = QtGui.QTableWidgetItem()
        self.tbPropriedades.setVerticalHeaderItem(23, item)
        item = QtGui.QTableWidgetItem()
        self.tbPropriedades.setVerticalHeaderItem(24, item)
        item = QtGui.QTableWidgetItem()
        self.tbPropriedades.setVerticalHeaderItem(25, item)
        item = QtGui.QTableWidgetItem()
        self.tbPropriedades.setVerticalHeaderItem(26, item)
        item = QtGui.QTableWidgetItem()
        self.tbPropriedades.setVerticalHeaderItem(27, item)
        self.tbPropriedades.horizontalHeader().setVisible(False)
        self.tbPropriedades.horizontalHeader().setCascadingSectionResizes(False)
        self.tbPropriedades.horizontalHeader().setStretchLastSection(True)
        self.lblImagem = QtGui.QLabel(JanelaListaAlimentos)
        self.lblImagem.setGeometry(QtCore.QRect(630, 30, 260, 171))
        self.lblImagem.setAutoFillBackground(True)
        self.lblImagem.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblImagem.setScaledContents(True)
        self.lblImagem.setAlignment(QtCore.Qt.AlignCenter)
        self.lblImagem.setObjectName("lblImagem")
        self.txtCarregarFoto = QtGui.QLineEdit(JanelaListaAlimentos)
        self.txtCarregarFoto.setGeometry(QtCore.QRect(630, 260, 235, 26))
        self.txtCarregarFoto.setObjectName("txtCarregarFoto")
        self.btCarregarFoto = QtGui.QToolButton(JanelaListaAlimentos)
        self.btCarregarFoto.setGeometry(QtCore.QRect(865, 260, 26, 25))
        self.btCarregarFoto.setObjectName("btCarregarFoto")
        self.label_3 = QtGui.QLabel(JanelaListaAlimentos)
        self.label_3.setGeometry(QtCore.QRect(630, 210, 201, 41))
        self.label_3.setPixmap(QtGui.QPixmap(MY_DIR_IMG + "carregar_foto.png"))
        self.label_3.setObjectName("label_3")
        
        
        
        self.btSalvar = QtGui.QDialogButtonBox(JanelaListaAlimentos)
        self.btSalvar.setGeometry(QtCore.QRect(800, 480, 101, 34))
        self.btSalvar.setStandardButtons(QtGui.QDialogButtonBox.Save)
        self.btSalvar.setObjectName("btSalvar")
        self.txtNome = QtGui.QLineEdit(JanelaListaAlimentos)
        self.txtNome.setGeometry(QtCore.QRect(330, 60, 291, 26))
        self.txtNome.setObjectName("txtNome")
        self.label_2 = QtGui.QLabel(JanelaListaAlimentos)
        self.label_2.setGeometry(QtCore.QRect(330, 0, 251, 60))
        self.label_2.setPixmap(QtGui.QPixmap(MY_DIR_IMG + "nome_alimento.png"))
        self.label_2.setObjectName("label_2")
        self.line = QtGui.QFrame(JanelaListaAlimentos)
        self.line.setGeometry(QtCore.QRect(300, 20, 20, 481))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.btModificar = QtGui.QPushButton(JanelaListaAlimentos)
        self.btModificar.setGeometry(QtCore.QRect(10, 480, 141, 28))
        self.btModificar.setObjectName("btModificar")
        self.btRemover = QtGui.QPushButton(JanelaListaAlimentos)
        self.btRemover.setGeometry(QtCore.QRect(151, 480, 141, 28))
        self.btRemover.setObjectName("btRemover")
        self.label_5 = QtGui.QLabel(JanelaListaAlimentos)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 281, 41))
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(JanelaListaAlimentos)
        QtCore.QObject.connect(self.btSalvar, QtCore.SIGNAL("clicked(QAbstractButton*)"), JanelaListaAlimentos.salvar)
        QtCore.QObject.connect(self.btModificar, QtCore.SIGNAL("clicked()"), JanelaListaAlimentos.modificar)
        QtCore.QObject.connect(self.btRemover, QtCore.SIGNAL("clicked()"), JanelaListaAlimentos.remover)
        QtCore.QMetaObject.connectSlotsByName(JanelaListaAlimentos)

    def retranslateUi(self, JanelaListaAlimentos):
        JanelaListaAlimentos.setWindowTitle(QtGui.QApplication.translate("JanelaListaAlimentos", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPropriedades.verticalHeaderItem(0).setText(QtGui.QApplication.translate("JanelaListaAlimentos", "Calorias", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPropriedades.verticalHeaderItem(1).setText(QtGui.QApplication.translate("JanelaListaAlimentos", "Proteinas", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPropriedades.verticalHeaderItem(2).setText(QtGui.QApplication.translate("JanelaListaAlimentos", "Ferro", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPropriedades.verticalHeaderItem(3).setText(QtGui.QApplication.translate("JanelaListaAlimentos", "Calcio", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPropriedades.verticalHeaderItem(4).setText(QtGui.QApplication.translate("JanelaListaAlimentos", "Fibra", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPropriedades.verticalHeaderItem(5).setText(QtGui.QApplication.translate("JanelaListaAlimentos", "Colesterol", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPropriedades.verticalHeaderItem(6).setText(QtGui.QApplication.translate("JanelaListaAlimentos", "Acido Folico", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPropriedades.verticalHeaderItem(7).setText(QtGui.QApplication.translate("JanelaListaAlimentos", "Gorduras Totais", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPropriedades.verticalHeaderItem(8).setText(QtGui.QApplication.translate("JanelaListaAlimentos", "Gordura Saturada", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPropriedades.verticalHeaderItem(9).setText(QtGui.QApplication.translate("JanelaListaAlimentos", "Gordura Monoinsaturada", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPropriedades.verticalHeaderItem(10).setText(QtGui.QApplication.translate("JanelaListaAlimentos", "Gordura Polinsaturada", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPropriedades.verticalHeaderItem(11).setText(QtGui.QApplication.translate("JanelaListaAlimentos", "Vitamina A", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPropriedades.verticalHeaderItem(12).setText(QtGui.QApplication.translate("JanelaListaAlimentos", "Vitamina C", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPropriedades.verticalHeaderItem(13).setText(QtGui.QApplication.translate("JanelaListaAlimentos", "Vitamina D", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPropriedades.verticalHeaderItem(14).setText(QtGui.QApplication.translate("JanelaListaAlimentos", "Vitamina E", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPropriedades.verticalHeaderItem(15).setText(QtGui.QApplication.translate("JanelaListaAlimentos", "Vitamina K", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPropriedades.verticalHeaderItem(16).setText(QtGui.QApplication.translate("JanelaListaAlimentos", "Vitamina B1", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPropriedades.verticalHeaderItem(17).setText(QtGui.QApplication.translate("JanelaListaAlimentos", "Vitamina B2", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPropriedades.verticalHeaderItem(18).setText(QtGui.QApplication.translate("JanelaListaAlimentos", "Vitamina B6", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPropriedades.verticalHeaderItem(19).setText(QtGui.QApplication.translate("JanelaListaAlimentos", "Vitamina B12", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPropriedades.verticalHeaderItem(20).setText(QtGui.QApplication.translate("JanelaListaAlimentos", "Fluor", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPropriedades.verticalHeaderItem(21).setText(QtGui.QApplication.translate("JanelaListaAlimentos", "Fosforo", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPropriedades.verticalHeaderItem(22).setText(QtGui.QApplication.translate("JanelaListaAlimentos", "Iodo", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPropriedades.verticalHeaderItem(23).setText(QtGui.QApplication.translate("JanelaListaAlimentos", "Magnesio", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPropriedades.verticalHeaderItem(24).setText(QtGui.QApplication.translate("JanelaListaAlimentos", "Potassio", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPropriedades.verticalHeaderItem(25).setText(QtGui.QApplication.translate("JanelaListaAlimentos", "Selenio", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPropriedades.verticalHeaderItem(26).setText(QtGui.QApplication.translate("JanelaListaAlimentos", "Sodio", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPropriedades.verticalHeaderItem(27).setText(QtGui.QApplication.translate("JanelaListaAlimentos", "Zinco", None, QtGui.QApplication.UnicodeUTF8))
        self.lblImagem.setText(QtGui.QApplication.translate("JanelaListaAlimentos", "Imagem", None, QtGui.QApplication.UnicodeUTF8))
        self.btCarregarFoto.setText(QtGui.QApplication.translate("JanelaListaAlimentos", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btModificar.setText(QtGui.QApplication.translate("JanelaListaAlimentos", "Modificar", None, QtGui.QApplication.UnicodeUTF8))
        self.btRemover.setText(QtGui.QApplication.translate("JanelaListaAlimentos", "Remover", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("JanelaListaAlimentos", "Caso queira adicionar um novo alimento a lista, adicione o alimento logo ao lado >", None, QtGui.QApplication.UnicodeUTF8))

